version: '3'

services:
    app:
        build: ./app
        # http://localhost:8080/index.php
        ports:
            - '8080:80'
        volumes:
            - ./src:/var/www/html
            - ./app/php.ini:/usr/local/etc/php/php.ini
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: php_db
            MYSQL_USER: php_user
            MYSQL_PASSWORD: php_pass
            TZ: 'Asia/Tokyo'
        volumes:
        - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
        - 3306:3306
